# Site settings
title: Raúl Morales-Juberías
job.title: "Associate Professor"
email: raul.moralesjuberias@nmt.edu

description: > # this means to ignore newlines until "baseurl:"
# Physics Associate Professor at New Mexico Tech.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  rmjuberias

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Associate Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""